# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fuckthis <- function(why) {
    .Call('_barrierALK_fuckthis', PACKAGE = 'barrierALK', why)
}

#' quickPredict
#'
#' Quickly predict the output of a spatial ALK model
#'
#' @param X the design matrix
#' @param beta the vector fixed effect parameters
#' @param A the A prediction matrix
#' @param ranX the predicted random effects
#' @param cohort group cohort of CRL
#' @param ranXind convert cohort to ranX cols
quickPredict <- function(X, beta, ranX, A, cohort, ranXind) {
    .Call('_barrierALK_quickPredict', PACKAGE = 'barrierALK', X, beta, ranX, A, cohort, ranXind)
}

quickPredictAR <- function(X, beta, Xr, A, cohort, year, ageTimeKey) {
    .Call('_barrierALK_quickPredictAR', PACKAGE = 'barrierALK', X, beta, Xr, A, cohort, year, ageTimeKey)
}

quickPredictB <- function(X, beta) {
    .Call('_barrierALK_quickPredictB', PACKAGE = 'barrierALK', X, beta)
}

predict_probs <- function(etas, ages, p_type) {
    .Call('_barrierALK_predict_probs', PACKAGE = 'barrierALK', etas, ages, p_type)
}

predict_full <- function(X, beta, ranX, A, cohort, ranXind, ages, p_type) {
    .Call('_barrierALK_predict_full', PACKAGE = 'barrierALK', X, beta, ranX, A, cohort, ranXind, ages, p_type)
}

predict_full_AR <- function(X, beta, Xr, A, cohort, year, ageTimeKey, ages, p_type) {
    .Call('_barrierALK_predict_full_AR', PACKAGE = 'barrierALK', X, beta, Xr, A, cohort, year, ageTimeKey, ages, p_type)
}

predict_fullB <- function(X, beta, ages, p_type) {
    .Call('_barrierALK_predict_fullB', PACKAGE = 'barrierALK', X, beta, ages, p_type)
}

age_fishB <- function(X, beta, ages, lf, lblen) {
    .Call('_barrierALK_age_fishB', PACKAGE = 'barrierALK', X, beta, ages, lf, lblen)
}

